- type: entity
  id: LittleCheesersServiceTechFabCircuitboard
  parent: ServiceTechFabCircuitboard
  name: little cheeser's service techfab machine board
  description: A machine printed circuit board for a little cheeser's service techfab
  components:
    - type: MachineBoard
      prototype: LittleCheesersServiceTechFab
